version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feijoada-auditor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-650yheft6jrw"
s3_prefix = "feijoada-auditor"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
